services:
  check-check-backend:
    image: check-check-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      BACKEND_BASE_URL:
      AUTH_BASE_URL:
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
