services:
  db:
    image: postgres:17
    container_name: pg-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: check-check-db
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    # volumes: for some reason voluemes prevented changes in this file to take effect
    #   - pg-data:/var/lib/postgresql/data

# volumes:
#   pg-data:
