nix:
  enable: true
  packages:
    - zlib.dev
    - zlib.out
    - postgresql_17

snapshot: nightly-2024-12-04

packages:
- contracts
- web-api
- telegram-bot
- infrastructure
- core
- smart-primitives
