nix:
  enable: true
  packages:
  - zlib.dev
  - zlib.out
  - postgresql_17

snapshot: lts-23.14

packages:
- web-api
- telegram-bot
- infrastructure
- core

extra-deps:
- git: https://github.com/danielambda/smart-primitives.git
  commit: 03193ff51a339bccaa3250f40b9d2fa032782824
- git: https://github.com/danielambda/check-check-backend-contracts.git
  commit: d00cdc3b2d85621a5afae21c81b6dbcb5bec32e5
