name: optics-utils
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
    - Optics.Tuppled

  dependencies:
  - base
  - optics

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
