name: core
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
    - Core.Receipts.Domain.Receipt
    - Core.Receipts.Domain.ReceiptItem
    - Core.Receipts.GetReceipt
    - Core.Receipts.MonadClasses.Fetching
    - Core.Receipts.MonadClasses.Repository

  dependencies:
  - smart-primitives

  - base
  - text
  - optics
  - mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
