### Get John Doe for viewing
POST localhost:8080/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMDkzNGVmYjEtNDBmNi00ZDYzLWJjNTItMmY2ZGQzY2M0NThhIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDEyMTU4MzgsImV4cCI6MTc0MTIxOTQzOCwiaWF0IjoxNzQxMjE1ODM4fQ.wuJu23quSmElekwiKLEVvrMGCox0Mc0Wntw1kOJ8h0o

{
  "initialBudget": 1000,
  "lowerBound": 100
}

### Apply 0 delta to John Doe budget
PATCH localhost:8080/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMDkzNGVmYjEtNDBmNi00ZDYzLWJjNTItMmY2ZGQzY2M0NThhIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDEyMTU4MzgsImV4cCI6MTc0MTIxOTQzOCwiaWF0IjoxNzQxMjE1ODM4fQ.wuJu23quSmElekwiKLEVvrMGCox0Mc0Wntw1kOJ8h0o

0

### Add 100 rubles to John Doe budget
PATCH localhost:8080/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMDkzNGVmYjEtNDBmNi00ZDYzLWJjNTItMmY2ZGQzY2M0NThhIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDEyMTU4MzgsImV4cCI6MTc0MTIxOTQzOCwiaWF0IjoxNzQxMjE1ODM4fQ.wuJu23quSmElekwiKLEVvrMGCox0Mc0Wntw1kOJ8h0o

10000

### Take 110 rubles from John Doe budget
PATCH localhost:8080/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMDkzNGVmYjEtNDBmNi00ZDYzLWJjNTItMmY2ZGQzY2M0NThhIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDEyMTU4MzgsImV4cCI6MTc0MTIxOTQzOCwiaWF0IjoxNzQxMjE1ODM4fQ.wuJu23quSmElekwiKLEVvrMGCox0Mc0Wntw1kOJ8h0o

-11000
