name: web-api
version: 0.1.0.0
executable:
  main: Main.hs
  source-dirs: src

  dependencies:
  - check-check-backend-contracts
  - smart-primitives

  - core
  - infrastructure

  - base
  - servant-server
  - servant-auth-server
  - servant-auth
  - http-conduit
  - aeson
  - wai
  - wai-cors
  - warp
  - bytestring
  - base64-bytestring
  - postgresql-simple
  - mtl
  - uuid
  - text
  - optics
  - resource-pool
  - time
  - jose
  - hedis

  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
