name: web-api
version: 0.1.0.0
executable:
  main: Main.hs
  source-dirs: src

  dependencies:
  - core
  - base >= 4.7 && < 5
  - servant-server
  - http-conduit
  - aeson
  - wai
  - warp
  - dotenv
  - bytestring
  - wai-cors
  - postgresql-simple
  - mtl
  - uuid
  - text
  - optics

  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
