name: contracts
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
    - CheckCheck.Contracts.API

  dependencies:
  - smart-primitives

  - base
  - servant
  - servant-auth
  - text
  - uuid
  - aeson
  - time

  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wredundant-constraints
