### Get all incoming requests
GET localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiZGQ4YjBjZjctMGM3NC00MjQ2LWI1YzQtYjlkZmQ4N2QxMGNmIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDE5ODk3ODAsImV4cCI6MTc0MTk5MzM4MCwiaWF0IjoxNzQxOTg5NzgwfQ.EwiU1uHxW5O82Ik1pqgSbcA7hXhUaZOYMZSLm7VrXEk

### Mark request as completed
PUT localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests/1bdad89f-f30f-4679-8731-8fa983a72b6d
Content-Type: application/json

{ "action": "markCompleted" }

### Pay for request with rounding
PUT localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests/53b6acd4-c274-4924-b007-4b6d18bfac46
Content-Type: application/json

{
  "action": "payFor",
  "roundingEps": 100,
  "roundingStrategy": "up"
}
