### Get all incoming requests
GET localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests

### Mark request as completed
PUT localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests/1bdad89f-f30f-4679-8731-8fa983a72b6d
Content-Type: application/json

{ "action": "markCompleted" }

### Pay for request
PUT localhost:8080/users/b220e714-d740-402d-b801-cf904fc3834b/incoming-requests/df082a76-7c85-4803-9f84-805a26c56c8d
Content-Type: application/json

{
  "action": "payFor"
}
