### Get me
GET localhost:8080/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMGM0ZjdiZDAtNWQ1Zi00NmY1LTgzNWQtMjU3YjBhNmQwMjM3IiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDE4MTc0MzMsImV4cCI6MTc0MTgyMTAzMywiaWF0IjoxNzQxODE3NDMzfQ.bDGGwryt19xPk4iHKMN3KW0L8BYLsyoie-xL68Aey34
