### Get me
GET localhost:8080/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiNWZmNTU5M2YtZmRmMi00ZTNkLWFlNTktMzYzYTI4ZmYwMjQwIiwidXNlcm5hbWUiOiJhYm9idXMifSwibmJmIjoxNzQxODIzNTkwLCJleHAiOjE3NDE4MjcxOTAsImlhdCI6MTc0MTgyMzU5MH0.fIOQAx_1_hFFusNvVJxtctqMmVbBUJzhXiRqe4qJhAw
