### Get me
GET localhost:8080/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMDkzNGVmYjEtNDBmNi00ZDYzLWJjNTItMmY2ZGQzY2M0NThhIiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDEyMTU4MzgsImV4cCI6MTc0MTIxOTQzOCwiaWF0IjoxNzQxMjE1ODM4fQ.wuJu23quSmElekwiKLEVvrMGCox0Mc0Wntw1kOJ8h0o


