### Get contacts
GET localhost:8080/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMGM0ZjdiZDAtNWQ1Zi00NmY1LTgzNWQtMjU3YjBhNmQwMjM3IiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDE4MjM0NzQsImV4cCI6MTc0MTgyNzA3NCwiaWF0IjoxNzQxODIzNDc0fQ.YHGd14wSAd1GCtGHsBbZvd9VoywfyybKcFyjr0dgxOc

### Create contact
POST localhost:8080/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMGM0ZjdiZDAtNWQ1Zi00NmY1LTgzNWQtMjU3YjBhNmQwMjM3IiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDE4MjM0NzQsImV4cCI6MTc0MTgyNzA3NCwiaWF0IjoxNzQxODIzNDc0fQ.YHGd14wSAd1GCtGHsBbZvd9VoywfyybKcFyjr0dgxOc
Content-Type: application/json

{
  "contactUserId": "5ff5593f-fdf2-4e3d-ae59-363a28ff0240",
  "contactName": "abobus"
}

### Create contact
DELETE localhost:8080/contacts/5ff5593f-fdf2-4e3d-ae59-363a28ff0240
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsidXNlcklkIjoiMGM0ZjdiZDAtNWQ1Zi00NmY1LTgzNWQtMjU3YjBhNmQwMjM3IiwidXNlcm5hbWUiOiJkYW5pZWxhbWJkYSJ9LCJuYmYiOjE3NDE4MjM0NzQsImV4cCI6MTc0MTgyNzA3NCwiaWF0IjoxNzQxODIzNDc0fQ.YHGd14wSAd1GCtGHsBbZvd9VoywfyybKcFyjr0dgxOc
