name: infrastructure
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
    - Infrastructure
    - Infrastructure.Common.Persistence
    - Infrastructure.Receipts.Fetching
    - Infrastructure.Receipts.PGRepository
    - Infrastructure.Users.PGRepository
    - Infrastructure.Users.Requests.PGRepository

  dependencies:
  - smart-primitives
  - core

  - base
  - http-conduit
  - aeson
  - bytestring
  - postgresql-simple
  - mtl
  - uuid
  - text
  - optics
  - time
  - unordered-containers

executables:
  init-db:
    main: InitDb.hs
    source-dirs: init-db
    dependencies:
    - infrastructure

    - base
    - postgresql-simple
    - mtl
    - text
    - bytestring
    - dotenv

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
