### Create group (minimal fields)
POST localhost:8080/groups HTTP/1.1
Content-Type: application/json

{
  "name": "groupname"
}

### Create group (all fields)
POST localhost:8080/groups HTTP/1.1
Content-Type: application/json

{
  "name": "groupname",
  "initialBudget": 5200,
  "creatorId": "b04207b6-afdf-423b-9738-f6a93c68fe74"
}

### Get group
GET localhost:8080/groups/80a7f167-23b3-481b-b39c-2aa3db334342
