### Send list request from John Doe to John Doe
POST localhost:8080/users/67aa7086-9c2c-422b-ab6d-a53f91c41b4a/outgoing-requests
Content-Type: application/json

{
  "list":[{"identity":"aboba","price":50,"quantity":59}],
  "recipientId":"67aa7086-9c2c-422b-ab6d-a53f91c41b4a"
}

### Send receipt item request from John Doe to John Doe
POST localhost:8080/users/67aa7086-9c2c-422b-ab6d-a53f91c41b4a/outgoing-requests
Content-Type: application/json

{
  "receiptQr": "t=20240902T1428&s=149.97&fn=7282440500182193&i=87743&fp=4159976508&n=1",
  "indexSelections":[{
    "recipientId":"67aa7086-9c2c-422b-ab6d-a53f91c41b4a",
    "indices":[0]
  }]
}
