name: smart-primitives
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
  - SmartPrimitives.Positive
  - SmartPrimitives.TextLenRange
  - SmartPrimitives.TextMaxLen
  - SmartPrimitives.TextMinLen

  dependencies:
  - base
  - text
  - bytestring
  - servant-server
  - aeson
  - postgresql-simple
  - optics

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
